server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**